version: '3.8'

services:
  heygen-voice-explorer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heygen-voice-explorer
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - VUE_APP_HEYGEN_API_KEY=${VUE_APP_HEYGEN_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app_network

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    ports:
      - '80:80'      # HTTP
      - '443:443'    # HTTPS
      - '81:81'      # Admin UI
    volumes:
      - ./data/nginx/data:/data
      - ./data/nginx/letsencrypt:/etc/letsencrypt
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 